#!/bin/bash

# CONTEXT: GUEST during PRE-CONSTRUCTION as ROOT
# PURPOSE: Setup apt-repo list so that we can connect to Percona's repo

set -e
set -o xtrace

[ -n "${GUEST_USERNAME}" ] || die "GUEST_USERNAME needs to be set to the user for the guest image"
[ -n "${RELEASE}" ] || die "RELEASE must be set to either Trusty or Precise"

# Add Percona GPG key
#mkdir -p /home/${GUEST_USERNAME}/.gnupg

# sometimes the primary key server is unavailable and we should try an
# alternate.  see
# https://bugs.launchpad.net/percona-server/+bug/907789.  Disable
# shell errexit so we can interrogate the exit code and take action
# based on the exit code. We will reenable it later.
function get_key_robust() {
    KEY=$1
    set +e

    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys ${KEY}

    if [ "$?" -ne "0" ];
    then
        echo "Trying alternate keyserver hkp://keys.gnupg.net"
        set -e
        apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-keys ${KEY}
        if [ "$?" -ne "0" ];
        then
            echo "Trying alternate keyserver hkp://pool.sks-keyservers.net"
            set -e
            apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys ${KEY}
        fi
    fi

    set -e
}

#get_key_robust 1C4CBDCDCD2EFD2A
#get_key_robust 9334A25F8507EFA5

# Add Percona repo
wget "https://repo.percona.com/apt/percona-release_latest.${RELEASE}_all.deb"
dpkg -i percona-release_latest.${RELEASE}_all.deb

