#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install basic services and applications

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt -qy install software-properties-common
apt-get --allow-unauthenticated -y install ntp apparmor-utils \
    python-dev libxml2-dev libxslt1-dev python-setuptools \
    python-sqlalchemy python-lxml \
    python-routes python-eventlet python-webob \
    python-pastedeploy python-paste python-netaddr \
    python-httplib2 python-iso8601 python-pexpect \
    python-migrate git python-mysqldb 

python /usr/lib/python2.7/dist-packages/easy_install.py pip
pip install pip --upgrade 
