- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - trove-functional-mysql
        - trove-scenario-mariadb-single:
            voting: false
        - trove-scenario-mariadb-multi:
            voting: false
        - trove-scenario-mysql-single
        - trove-scenario-mysql-multi
        - trove-scenario-postgresql-single:
            voting: false
        - trove-scenario-postgresql-multi:
            voting: false
        - trove-scenario-pxc-single:
            voting: false
        - trove-scenario-pxc-multi:
            voting: false
        - trove-scenario-redis-single:
            voting: false
        - trove-scenario-redis-multi:
            voting: false
        - trove-tox-fakemodetests
        - trove-tox-apiexamples
        - openstack-tox-pylint
    gate:
      queue: trove
      jobs:
        - trove-functional-mysql
        - trove-scenario-mysql-single
        - trove-scenario-mysql-multi
        - trove-tox-fakemodetests
        - trove-tox-apiexamples
        - openstack-tox-pylint
    experimental:
      jobs:
        - trove-grenade
        - trove-scenario-cassandra-single
        - trove-scenario-cassandra-multi
        - trove-scenario-couchbase-single
        - trove-scenario-couchdb-single
        - trove-scenario-mongodb-single
        - trove-scenario-mongodb-multi
        - trove-scenario-percona-single
        - trove-scenario-percona-multi

    post:
      jobs:
        - openstack-tox-cover
- job:
    name: trove-functional-mysql
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-functional-dsvm-mysql/run.yaml
    post-run: playbooks/legacy/trove-functional-dsvm-mysql/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-grenade
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-dsvm-trove/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-trove/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-cassandra-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-cassandra-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-cassandra-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-cassandra-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-cassandra-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-cassandra-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-couchdb-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-couchdb-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-couchdb-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-couchbase-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-couchbase-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-couchbase-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-mariadb-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-mariadb-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-mariadb-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-mariadb-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-mariadb-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-mariadb-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-mongodb-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-mongodb-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-mongodb-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-mongodb-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-mongodb-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-mongodb-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-mysql-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-mysql-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-mysql-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-mysql-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-mysql-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-mysql-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-percona-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-percona-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-percona-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-percona-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-percona-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-percona-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-postgresql-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-postgresql-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-postgresql-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-postgresql-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-postgresql-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-postgresql-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-pxc-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-pxc-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-pxc-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-pxc-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-pxc-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-pxc-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-redis-single
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-redis-single/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-redis-single/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-scenario-redis-multi
    parent: legacy-dsvm-base
    run: playbooks/legacy/trove-scenario-dsvm-redis-multi/run.yaml
    post-run: playbooks/legacy/trove-scenario-dsvm-redis-multi/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/diskimage-builder
      - openstack/python-troveclient
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard

- job:
    name: trove-tox-fakemodetests
    parent: openstack-tox-py27
    vars:
      tox_envlist: fakemodetests

- job:
    name: trove-tox-apiexamples
    parent: openstack-tox-py27
    vars:
      tox_envlist: apiexamples
