#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see trovestack functions_qemu

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
add-apt-repository -y cloud-archive:queens
