#!/bin/bash
mkdir -p /etc/monasca/agent/conf.d/
if [ ${SERVICE_TYPE} == "redis" ];then
  cat >/etc/monasca/agent/conf.d/redisdb.yaml <<_EOF_
# (C) Copyright 2015 Hewlett Packard Enterprise Development Company LP

init_config:

instances:
   -   host: "localhost"
       port: "6379"

_EOF_

elif [ ${SERVICE_TYPE} == "postgresql" ];then
   cat >/etc/monasca/agent/conf.d/postgres.yaml <<_EOF_

# (C) Copyright 2015 Hewlett Packard Enterprise Development Company LP

init_config:

instances:
  -   host: localhost
      port: 5432
      username: os_admin
      password:
      dbname: os_admin

#  Custom-metrics section

#  You can now track per-relation (table) metrics
#  You need to specify the list. Each relation
#  generates a lot of metrics (10 + 10 per index)
#  so you want to only use the ones you really care about

#       relations:
#            - my_table
#            - my_other_table
_EOF_

fi