#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

# NOTE(vkmc): Using MariaDB repositories is required
# https://mariadb.com/kb/en/mariadb/installing-mariadb-deb-files/
apt-get -y install software-properties-common
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/10.1/ubuntu xenial main'

# Pin MariaDB repository
sudo echo -e "Package: *\nPin: origin ftp.osuosl.org\nPin-Priority: 1000" > /etc/apt/preferences.d/mariadb.pref

apt-get -y update
apt-get -y install socat percona-xtrabackup
apt-get -y install libmariadbclient18 mariadb-server

# Copy vdbaas procedure to /var/lib/trove
TMP_HOOKS_DIR="/tmp/in_target.d"
echo "Copy vdbaas extra-data to /var/lib/trove"
cp -rf ${TMP_HOOKS_DIR}/extra-data.d/mariadb-extra-data.d/* /var/lib/trove


if [ -e /etc/init/mysql.conf ]; then
    rm -f /etc/init/mysql.conf
fi

if [ -e /var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/mariadb.service ]; then
   rm -f /var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/mariadb.service
fi

if [ -e /var/lib/systemd/deb-systemd-helper-enabled/mysql.service]; then
   rm -f /var/lib/systemd/deb-systemd-helper-enabled/mysql.service
fi

if [ -e /etc/init.d/mysql]; then
   rm -f /etc/init.d/mysql
fi

