#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

#set -e
#set -o xtrace
#export DEBIAN_FRONTEND=noninteractive
echo "mysql ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
